spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/similarity_db
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB